// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgu0f8HhzAJJTL200EgtGb0BJ_EUncCiM',
    appId: '1:748610337219:web:2c77ca865238351e88a576',
    messagingSenderId: '748610337219',
    projectId: 'priority-soft-testapp',
    authDomain: 'priority-soft-testapp.firebaseapp.com',
    storageBucket: 'priority-soft-testapp.appspot.com',
    measurementId: 'G-FZ87F3WKGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlHCX_hy7CoEQjJ8jPiufvvRlyQB715Ho',
    appId: '1:748610337219:android:28bb5c396114859588a576',
    messagingSenderId: '748610337219',
    projectId: 'priority-soft-testapp',
    storageBucket: 'priority-soft-testapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1fW0Pp-H0ONfYF6SN04hUFnbJleUe-qc',
    appId: '1:748610337219:ios:832ee8a5b0dff8f088a576',
    messagingSenderId: '748610337219',
    projectId: 'priority-soft-testapp',
    storageBucket: 'priority-soft-testapp.appspot.com',
    iosBundleId: 'com.example.priorityshoftTestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1fW0Pp-H0ONfYF6SN04hUFnbJleUe-qc',
    appId: '1:748610337219:ios:832ee8a5b0dff8f088a576',
    messagingSenderId: '748610337219',
    projectId: 'priority-soft-testapp',
    storageBucket: 'priority-soft-testapp.appspot.com',
    iosBundleId: 'com.example.priorityshoftTestapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgu0f8HhzAJJTL200EgtGb0BJ_EUncCiM',
    appId: '1:748610337219:web:0e3544013c13bb6688a576',
    messagingSenderId: '748610337219',
    projectId: 'priority-soft-testapp',
    authDomain: 'priority-soft-testapp.firebaseapp.com',
    storageBucket: 'priority-soft-testapp.appspot.com',
    measurementId: 'G-3R9FWGPMSC',
  );
}
